title: TyraMisu Tech
author: Tyra
email: tyra.lyn.earl@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  A blog outlining my journey through learning to be a software developer, working remotely, working with a disability, mental health, and more. 

# social links
twitter_username: TyraEarl # DO NOT include the @ character, or else the build will fail!
github_username:  Ravalyn # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
